// <auto-generated />
using EvGDecisionAnalysis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvGDecisionAnalysis.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("EvGDecisionAnalysis.Models.NPVResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CalculatedNPV")
                        .HasColumnType("REAL");

                    b.Property<double>("NPVE1")
                        .HasColumnType("REAL");

                    b.Property<double>("NPVE2")
                        .HasColumnType("REAL");

                    b.Property<double>("PE1")
                        .HasColumnType("REAL");

                    b.Property<double>("PE2")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("NPVResults");
                });
#pragma warning restore 612, 618
        }
    }
}
