name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore EvGDecisionAnalysis/EvGDecisionAnalysis.csproj

    - name: Build the project
      run: dotnet build EvGDecisionAnalysis/EvGDecisionAnalysis.csproj --configuration Release --no-restore

    - name: Publish the project
      run: dotnet publish EvGDecisionAnalysis/EvGDecisionAnalysis.csproj --configuration Release --output ./publish --no-build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t mywpfapp:latest .
        docker tag mywpfapp:latest ${{ secrets.DOCKER_USERNAME }}/mywpfapp:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mywpfapp:latest
